# SPDX-License-Identifier: Apache-2.0 OR MIT
# SPDX-FileCopyrightText: 2025 AUSP59 <alanursapu@gmail.com>

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: clang-format
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: |
          sudo apt-get update && sudo apt-get install -y clang-format
          git ls-files '*.h' '*.hpp' '*.c' '*.cc' '*.cpp' | xargs -I{{}} clang-format --dry-run --Werror {{}}
