# SPDX-License-Identifier: Apache-2.0 OR MIT
# SPDX-FileCopyrightText: 2025 AUSP59 <alanursapu@gmail.com>

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: grype
on: [push, pull_request]
jobs:
  scan:
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/scan-action@v4
        with:
          path: .
          fail-build: false
          severity-cutoff: high
