# SPDX-License-Identifier: Apache-2.0 OR MIT
# SPDX-FileCopyrightText: 2025 AUSP59 <alanursapu@gmail.com>

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: trivy-scan
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  fs-scan:
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t biosimx:ci .
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'biosimx:ci'
          format: 'table'
          exit-code: '0'
